"""This file contains the Substrate class, which is used to define the structure of the neural network that will be generated by the CPPN. 
The substrate is defined by its shape, an array of the form [[x1, x2, x3, l1], [y1, y2, y3, l2], [z1, z2, z3, l3]] where x1 is the number of neurons in the first dimension of the first layer, x2 in the second dimension and so on. the number of list is the number of layer. 
the last element of each list also indicates the layer of the neural network. 
For Hyperneat to work, we need to obtain the coordinates of each neurons in the substrate, each neurons must have its coordinates between -1 and 1 so that the cppn can process them."""

import numpy as np
import itertools as it 

class Substrate :

    def __init__(self, shape: np.ndarray) :
        """We keep in memory the dimensions of the substrate and the coordinates of the input, 
        output and hidden layers. hidden layers are stored in a list of arrays because many hidden layers are possible.
        shape is for example [[3, 3, 3, 1], [2, 2, 2, 2], [1, 1, 1, 3]] for a substrate with 3 layers."""
        self.dimensions = len(shape[0])
        self.input_coordinates = Substrate._dimension_into_coordinate_layer(shape[0])
        self.output_coordinates = Substrate._dimension_into_coordinate_layer(shape[-1])
        self.hidden_coordinates = [Substrate._dimension_into_coordinate_layer(layer) for layer in shape[1:-1]]

    @staticmethod
    def _dimension_into_coordinate_layer(array_of_shape: np.ndarray) -> np.ndarray :
        """Takes an array ie [2, 3, 4, 1] is for dim x, 2 is the number of coordinates in the first dimension, 3 in the second, 4 in the third and 1 in the last.
        The last one is the layer of the neural network, we return every possible coordinate for the neurons on the current layer ie 1 here. 
        I have made some change and I will put the coordinate layer on the first dimension of the array"""
        interval_array = []
        last_dimension_coordinate = [array_of_shape[-1]]
        for x in array_of_shape[1:] :
            interval_one_dimension = np.linspace(-1.0, 1.0, x) if (x > 1) else [0.0]
            interval_array.append(interval_one_dimension)
        return np.array(list(it.product(*interval_array, last_dimension_coordinate)))
    
    @staticmethod
    def morph_substrate_shape_builder(robot_size) : 
        """This function take the robot size and based on it, creates the shape that will be passe to the substrate class to create the substrate for the morpho"""
        # this here will be the number of neurons on 1 dimensions of the layer 
        intermediate_layer = (1 + robot_size)//2
        shape = [
            [1, 1, 1, 1],
            [intermediate_layer, intermediate_layer, 3, 2],
            [robot_size, robot_size, 5, 3],
        ]
        return Substrate(shape)

    @staticmethod 
    def control_substrate_shape_builder(robot_size, grid_input_size) :
        """This function take the robot size and the grid input size and based on it, 
        creates the shape that will be passed to the bustrate class to create the substrate for the control."""
        intermediate_layer = (grid_input_size + robot_size)//2
        shape = [
            [grid_input_size, grid_input_size, 1, -1],
            [intermediate_layer, intermediate_layer, 1, -2],
            [robot_size, robot_size, 1, -3]
        ]
        return Substrate(shape)
    

class SubstrateBuilder:
    """Substrate will entirely be defined by the sex of the indivual, for the moment i ll have only one sex and not two"""
    def __init__(self, config):
        self.config = config


    def read_sex(self, chromosome2) : 
        return "female"
    
    
    def shape_into_coordinates(self, shape) :
        """basically turn the shape in all of the coordinate for each layer, first indices is the layer"""
        number_of_layer = len(shape)
        first_indice = 1/number_of_layer
        all_interval = []

        if np.sign(shape[0][0]) == 1 :
            first_dim_locations = np.linspace(first_indice, 1.0, number_of_layer)

        elif np.sign(shape[0][0]) == -1 :
            first_dim_locations = np.linspace(-1.0, -first_indice, number_of_layer)

        for layer in shape :
            indice = abs(layer[0]) - 1
            location = first_dim_locations[indice]
            interval_array = []

            for x in layer[1:] :
                interval_one_dimension = np.linspace(-1.0, 1, x) if (x>1) else [0.0]
                interval_array.append(interval_one_dimension)

            all_coords = list(it.product([location], *interval_array))
            all_interval.append(all_coords)
        
        return all_interval


    def extract_body_network_shape(self, config):

        body_shape = config.body_shape
        shape_of_substrate = [
            [1, 1, 1, 1], 
            [2, body_shape[0], body_shape[1], 2], 
            [3, body_shape[0], body_shape[1], 5]
        ]
        return shape_of_substrate 
        
    def extract_controller_network_shape(self, grid_input_size, config) :
        body_shape = config.body_shape
        controller_shape = [
            [-1, grid_input_size, grid_input_size, 1], 
            [-2, grid_input_size//2, grid_input_size//2, body_shape[0]//2], 
            [-3, body_shape[0], body_shape[1], 1]
        ]
        return controller_shape


            


        


     

